CREATE TABLE [TestDB].[dbo].[Candidates]
(
[Id]  BiGINT  NOT NULL UNIQUE,
[Name] VARCHAR(100) NOT NULL,
[Email] VARCHAR(100) NOT NULL,
[Phone] VARCHAR(100) NOT NULL DEFAULT '0000-000-000-000',
CONSTRAINT [PK_CANDIDATES] PRIMARY KEY CLUSTERED ([Id])
)